"""initial schema

Revision ID: e64b21dcf7c7
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = 'e64b21dcf7c7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'owner', 'admin')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('carts',
    sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_carts_latitude')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_carts_longitude')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_carts_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index(op.f('ix_carts_category'), 'carts', ['category'], unique=False)
    op.create_index(op.f('ix_carts_is_open'), 'carts', ['is_open'], unique=False)
    op.create_index('ix_carts_location', 'carts', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_carts_longitude'), 'carts', ['longitude'], unique=False)
    op.create_index(op.f('ix_carts_owner_id'), 'carts', ['owner_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'reviewing', 'resolved', 'dismissed')", name=op.f('ck_reports_status')),
    sa.CheckConstraint("target_type IN ('user', 'cart')", name=op.f('ck_reports_target_type')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index('ix_reports_target', 'reports', ['target_type', 'target_id'], unique=False)
    op.create_table('follows',
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cart_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_follows_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_follows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('user_id', 'cart_id', name='uq_follows_user_cart')
    )
    op.create_index(op.f('ix_follows_cart_id'), 'follows', ['cart_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('cart_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_notifications_cart_id_carts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_cart_id'), 'notifications', ['cart_id'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # Dropping tables removes their indexes; do not drop FK-supporting indexes first.
    op.drop_table('notifications')
    op.drop_table('follows')
    op.drop_table('reports')
    op.drop_table('carts')
    op.drop_table('users')
